import fs from 'node:fs';
const rows=[
['deluxe-room','Deluxe Room','Stay','A GOOD NIGHT’S REST','A comfortable room for a focused work trip, a city visit, or a quiet overnight stay.','deluxe',['business','families'],3800],
['suite-room','Suite Room','Stay','ROOM TO UNWIND','More room to relax when your stay deserves a little extra space.','suite',['couples','families'],4900],
['executive-deluxe','Executive Deluxe Room','Stay','BUSINESS & PLEASURE','A polished base for business travel, family visits, and extended comfort.','executive',['business','couples'],4300],
['executive-suite','Executive Suite Room','Stay','MAKE YOURSELF AT HOME','Ask about a larger executive setup for longer or more special stays.','suite-living',['business','families'],null],
['halcons-dining','Halcons’ Dining','Dine','A PLACE AT THE TABLE','Filipino dishes, drinks, and a comfortable place to meet over a meal.','terrace',['couples','families','groups'],null],
['pool-day','Pool Day','Leisure','SLOW AFTERNOONS','Make time for a refreshing swim and a slower afternoon at the hotel.','hotel-pool',['families','couples'],null],
['wellness','Wellness Services','Leisure','TAKE A BREATHER','Ask about massage, sauna, hot tub, and the latest wellness schedule.','lobby',['couples','business'],null],
['recreation','Basketball & Recreation','Leisure','A LITTLE PLAY TIME','Add a little movement to your stay with available recreation facilities.','entrance',['families','groups'],null],
['weddings','Wedding Events','Events','YOUR NEXT CHAPTER','Bring your people together with venue, food, styling, and hotel support.','wedding',['couples','celebrations'],null],
['seminars','Seminar & Conference','Events','IDEAS COME TOGETHER','A focused gathering with venue setup, dining, and accommodation options.','conference',['business','groups'],null],
['socials','Socials & Reunions','Events','EVERY REASON TO CELEBRATE','Bring birthdays, reunions, debuts, and celebrations together.','celebration',['families','celebrations'],null],
['group-stay','Room Block for Groups','Events','KEEP EVERYONE CLOSE','Coordinated accommodation for weddings, seminars, and family events.','deluxe',['groups','business'],null]
];
const roomDetails=[['Occupancy','Ask reservations to confirm adults, children, and extra-bed options.'],['Bed configuration','Room layouts vary. Please confirm your preferred bed setup.'],['Room size','Contact reservations for dimensions and accessibility details.'],['In-room comforts','Ask about air conditioning, Wi-Fi, television, refrigerator, and room service for your selected category.'],['Bathroom','Confirm hot and cold water, toiletries, towels, and bathroom accessibility.'],['Breakfast & pool access','Inclusions depend on your confirmed room offer.'],['Check-in & check-out','Please confirm current arrival and departure times with reservations.'],['Children & extra guests','Child ages, extra beds, and applicable charges must be confirmed.'],['Cancellation','Your written reservation confirmation will state deposit and cancellation terms.']];
const eventDetails=[['Seating & capacity','Capacity depends on the venue and approved layout. Request a current floor plan.'],['Layouts','Ask about banquet, classroom, theatre, and other available setups.'],['Catering & styling','Request current menus, dietary options, styling inclusions, and supplier terms.'],['Audio-visual equipment','Confirm microphones, screens, projection, power, and technical support.'],['Parking & room blocks','Tell us your transport and accommodation requirements.'],['Planning timeline','Share your preferred date, decision deadline, and setup schedule.'],['Deposits & cancellation','Request written deposit, cancellation, overtime, guest-count, outside-supplier, and damage terms.']];
const services=rows.map(([id,title,category,badge,description,img,audience,price])=>({id,title,category,badge,description,image:`/images/${img}.webp`,alt:`Filipiniana Hotel Calapan ${img.replaceAll('-',' ')}`,audience,price,approved:false,effectiveDate:'',capacity:category==='Stay'?'Occupancy and bed setup on request':category==='Events'?'Capacity confirmed for your layout':'Schedule and access on request',action:category==='Events'?'Request a proposal':category==='Stay'?'View room':'Ask about this',details:(category==='Stay'?roomDetails:category==='Events'?eventDetails:[['Hours & availability','Ask the hotel for the current operating schedule before visiting.'],['Rates & inclusions','The team will confirm current prices and what is included.'],['Special requests','Please tell us about dietary, accessibility, supervision, or group requirements.']]).map(([label,value])=>({label,value}))}));
const data={hotel:{name:'Filipiniana Hotel Calapan',phone:'(043) 288-6624',mobile:'0917-392-8712',email:'filipinianahotel@yahoo.com',address:'M. Roxas St., Brgy. Sto. Niño, Calapan City, Oriental Mindoro 5200, Philippines',facebook:'https://www.facebook.com/filipinianahotel',instagram:'https://www.instagram.com/filipinianacalapan',messenger:'https://m.me/filipinianahotel',maps:'https://www.google.com/maps/search/?api=1&query=Filipiniana+Hotel+Calapan'},services,
faqs:[{question:'How do I reserve a room?',answer:'Send an inquiry with your check-in and check-out dates, room preference, and guest count. The reservations team will confirm availability, the final rate, inclusions, and payment instructions. An inquiry does not reserve a room.'},{question:'Where is the hotel located?',answer:'Find us on M. Roxas Street in Barangay Sto. Niño, Calapan City, near Xentro Mall and behind Landbank Calapan. Open our Google Maps directions for the route from your starting point.'},{question:'What are the check-in and check-out times?',answer:'Please confirm the current times with reservations. Tell the team if you need early arrival or late departure; availability and charges may apply.'},{question:'Is pool access included with my stay?',answer:'Pool access, guest limits, outside-visitor rates, and schedules depend on your confirmed offer. Ask before visiting. Children require responsible adult supervision, and weather or maintenance may affect access.'},{question:'Can you arrange an event with accommodation?',answer:'Yes, ask about coordinating your venue, dining, and a block of guest rooms. The team will confirm the available layouts, capacity, menus, equipment, and current package terms.'},{question:'Can you help with accessibility or special requirements?',answer:'Contact the team before booking to confirm step-free access, room and bathroom arrangements, dietary requirements, transport assistance, or other needs.'},{question:'What if something in my room needs attention?',answer:'Contact reception promptly with the room number and issue so the team can assist. Ask before booking if reliable hot water or a particular amenity is essential to your stay.'}],
policies:[{title:'Booking & cancellations',body:'A reservation is confirmed only after the hotel issues a written confirmation and the required payment terms are met. Ask for current check-in, check-out, deposit, cancellation, no-show, children, extra-bed, tax, and refund terms before paying.'},{title:'Pool & wellness',body:'Confirm hours, age restrictions, admission fees, staying-guest inclusions, and outside-guest access before visiting. Children must be supervised by a responsible adult. Follow posted safety instructions; weather and maintenance may close facilities. Contact reception for on-site assistance or call 911 in an emergency. Ask staff about any health or accessibility requirements before using wellness facilities.'},{title:'Events & outside suppliers',body:'Your written event agreement must confirm venue capacity, layout, guest count, deposits, cancellation, overtime, catering, outside suppliers, setup and teardown, equipment, damage responsibility, and accommodation blocks. Do not assume any package inclusion before receiving a proposal.'},{title:'Privacy & your information',body:'When you send an inquiry, we use your contact and planning information to respond and arrange the requested service. Newsletter consent is separate and optional. Submitted details are stored privately and may be processed by our email delivery provider. We do not sell your details. Request access, correction, or deletion through filipinianahotel@yahoo.com. Inquiry records are scheduled for deletion after 90 days unless needed for an active booking or legal obligation. Newsletter recipients can unsubscribe using the link in their confirmation or any future campaign.'}],testimonials:[],menu:[],
facilities:[{title:'Outdoor swimming pool',description:'A refreshing pause, surrounded by tropical greenery.',status:'Ask for hours, admission, and guest inclusions.'},{title:'Children’s pool',description:'Ask the team about the current children’s swimming area.',status:'Confirm age rules. Adult supervision is required.'},{title:'Massage, sauna & hot tub',description:'Make a little time to unwind during your stay.',status:'Services and appointments require confirmation.'},{title:'Basketball & recreation',description:'Leave a little room in the day for a friendly game.',status:'Ask for access, equipment, and group arrangements.'},{title:'Garden & outdoor spaces',description:'Step outside and enjoy a quieter moment.',status:'Outdoor use depends on weather and hotel activity.'},{title:'Karaoke & videoke',description:'Bring your group together for a little music.',status:'Ask about booking, hours, charges, and noise rules.'}],gallery:[['hotel-pool','Hotel, landscaped bridge, and outdoor pool','Leisure'],['deluxe','Guest room with two beds and warm wood finishes','Stay'],['suite','Suite bedroom and seating area','Stay'],['executive','Guest room with tropical feature wall','Stay'],['suite-living','Suite living and dining area','Stay'],['terrace','Halcons’ covered dining terrace','Dine'],['restaurant','Indoor dining at Halcons’ Bar and Resto','Dine'],['wedding','Decorated wedding reception at the hotel','Events'],['conference','Classroom setup for a seminar','Events'],['celebration','Social celebration styling at the hotel','Events'],['lobby','Hotel lobby and lounge','Stay'],['entrance','Filipiniana Hotel entrance','Stay']].map(([img,alt,category])=>({image:`/images/${img}.webp`,alt,category}))};
fs.writeFileSync(new URL('../content/hotel.json',import.meta.url),JSON.stringify(data,null,2));
